VersionsDatabase = {
    '0': '''CREATE TABLE MENSAGEM_BASE_EMAIL (UMA_POR_VEZ VARCHAR(32000) CHARACTER SET WIN1252, TODAS_DE_UMA_VEZ VARCHAR(32000) CHARACTER SET WIN1252);´
    CREATE TABLE MENSAGEM_BASE_PROMISSORIA_EMAIL (MENSAGEM  VARCHAR(32765) CHARACTER SET WIN1252);´
    CREATE TABLE MENSAGEM_BASE_PROMISSORIA_ZAP (MENSAGEM  VARCHAR(32765) CHARACTER SET WIN1252);´
    CREATE TABLE MENSAGEM_BASE_ZAP (UMA_POR_VEZ VARCHAR(32000) CHARACTER SET WIN1252, TODAS_DE_UMA_VEZ  VARCHAR(32000) CHARACTER SET WIN1252);´
    CREATE GENERATOR GEN_MENSAGENS_EMAIL_ID;´
    CREATE TABLE MENSAGENS_EMAIL (ID INTEGER NOT NULL, CODCLI INTEGER, COBRANCA VARCHAR(32765) CHARACTER SET WIN1252, ENVIADO VARCHAR(30) CHARACTER SET WIN1252, TIPO_DA_COBRANCA VARCHAR(20) CHARACTER SET WIN1252, N_DOCUMENTO VARCHAR(50) CHARACTER SET WIN1252);´
    ALTER TABLE MENSAGENS_EMAIL ADD CONSTRAINT PK_MENSAGENS_EMAIL PRIMARY KEY (ID);´
    CREATE OR ALTER TRIGGER MENSAGENS_EMAIL_BI FOR MENSAGENS_EMAIL ACTIVE BEFORE INSERT POSITION 0 as begin if (new.id is null) then new.id = gen_id(gen_mensagens_email_id,1); end;´
    CREATE GENERATOR GEN_MENSAGENS_ZAP_ID;´
    CREATE TABLE MENSAGENS_ZAP(ID INTEGER NOT NULL, CODCLI INTEGER, COBRANCA VARCHAR(32765) CHARACTER SET WIN1252, TEMPO INTEGER, ENVIADO VARCHAR(30) CHARACTER SET WIN1252, TIPO_DA_COBRANCA VARCHAR(20) CHARACTER SET WIN1252, TEMPO_MENSAGEM_BASE INTEGER, N_DOCUMENTO VARCHAR(50) CHARACTER SET WIN1252);´
    ALTER TABLE MENSAGENS_ZAP ADD CONSTRAINT PK_MENSAGENS_ZAP PRIMARY KEY (ID);´
    CREATE OR ALTER TRIGGER MENSAGENS_ZAP_BI FOR MENSAGENS_ZAP ACTIVE BEFORE INSERT POSITION 0 as begin if (new.id is null) then new.id = gen_id(gen_mensagens_zap_id,1); end;´
    CREATE TABLE EMAIL_ZAP (EMAIL VARCHAR(100) CHARACTER SET WIN1252, SENHA VARCHAR(30) CHARACTER SET WIN1252, TITULO VARCHAR(250) CHARACTER SET WIN1252, SUB_TITULO VARCHAR(250) CHARACTER SET WIN1252);´
    CREATE TABLE NUMERO_ZAP (NUMERO_DE_TELEFONE VARCHAR(20) CHARACTER SET WIN1252, SENHA VARCHAR(20) CHARACTER SET WIN1252);´
    CREATE TABLE CFG_COBRANCA (ID INTEGER NOT NULL, DB_VERSAO VARCHAR(20));´
    ALTER TABLE CFG_COBRANCA ADD CONSTRAINT PK_CFG_COBRANCA PRIMARY KEY (ID);´
    INSERT INTO CFG_COBRANCA (ID, DB_VERSAO) VALUES ('1', '0');''',

    '4.3.3.7': '''ALTER TABLE MENSAGENS_ZAP DROP DESTINATARIO;´
    ALTER TABLE MENSAGENS_ZAP DROP NOMCLI;´
    ALTER TABLE MENSAGENS_EMAIL DROP TEMPO_MENSAGEM_BASE;´
    ALTER TABLE MENSAGENS_EMAIL DROP TEMPO;´
    ALTER TABLE MENSAGENS_EMAIL DROP DESTINATARIO;´
    ALTER TABLE MENSAGENS_EMAIL DROP NOMCLI;´
    ALTER TABLE MENSAGENS_ZAP ALTER ENVIADO TYPE VARCHAR(30) CHARACTER SET WIN1252;´
    ALTER TABLE MENSAGENS_EMAIL ALTER ENVIADO TYPE VARCHAR(30) CHARACTER SET WIN1252;´
    ALTER TABLE EMAIL_ZAP ADD TITULO VARCHAR(250) CHARACTER SET WIN1252 COLLATE WIN1252, ADD SUB_TITULO VARCHAR(250) CHARACTER SET WIN1252 COLLATE WIN1252;´
    UPDATE CFG_COBRANCA SET DB_VERSAO = '4337' WHERE ID = 1;'''
}
print(sorted(VersionsDatabase))
